<?php

namespace App\Http\Controllers;

use App\Models\AutoGenerateFoodSpend;
use App\Models\ExerciseBook;
use App\Models\FeeTransaction;
use App\Models\IncludeAutogenerateDailyFood;
use App\Models\Student;
use App\Models\StudentAccessory;
use App\Models\TextBook;
use RealRashid\SweetAlert\Facades\Alert;

use Illuminate\Http\Request;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Contracts\Support\Renderable
     */
    public function index()
    {
        
        $include_auto_generate_food = IncludeAutogenerateDailyFood::all();
        $check_store_values = AutoGenerateFoodSpend::all();
        $students = Student::all();
        $books = TextBook::all();
        $fees = FeeTransaction::all();
        $exercise_books = ExerciseBook::all();
        $remaining_books = StudentAccessory::where('name', 'Exercise books')->get();
        if (isset($include_auto_generate_food[0])) {
            
if (!isset($check_store_values[0])) {
    return redirect(route('daily_food_used'));
} else {
    return view('home',[
        'students' => $students,
        'books'=> $books,
        'fees' => $fees,
        'exercise_books' => $exercise_books,
        'remaining_books' => $remaining_books
    ]);
}
        } else {
            return view('home',[
                'students' => $students,
                'books'=> $books,
                'fees' => $fees,
                'exercise_books' => $exercise_books,
                'remaining_books' => $remaining_books
            ]);
        }
        


       
    }
}