<?php

namespace App\Http\Controllers;

use App\Models\IncludeAutogenerateDailyFood;
use App\Models\School;
use Illuminate\Http\Request;

class SettingsController extends Controller
{
    public function settings()
    {
        $school_settings = School::all();
        $include_auto_generate_food = IncludeAutogenerateDailyFood::all();
        return view('pages.settings',[
            'school'=>$school_settings,
            'include_auto_generate' => $include_auto_generate_food
        ]);
    }
}